# Generated by Django 3.0.3 on 2020-03-02 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webexample', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='slug',
            field=models.SlugField(default=1231, unique=True),
            preserve_default=False,
        ),
    ]
