# Generated by Django 3.0.3 on 2020-03-09 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webexample', '0004_auto_20200306_2317'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='fullname',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='author',
            name='second_name',
            field=models.CharField(db_index=True, default=123, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='genre',
            name='info',
            field=models.TextField(default=3, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='author',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='info',
            field=models.TextField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='book',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
