# Generated by Django 3.0.3 on 2020-03-09 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webexample', '0005_auto_20200309_0228'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='info',
            field=models.TextField(default=123, max_length=100),
            preserve_default=False,
        ),
    ]
