# Generated by Django 3.0.3 on 2020-03-09 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webexample', '0006_author_info'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='recom_ages',
            new_name='recomAge',
        ),
    ]
