# Generated by Django 3.0.3 on 2020-03-10 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webexample', '0008_auto_20200310_0304'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='photo',
            field=models.CharField(default=123, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='photo',
            field=models.CharField(default=123, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='genre',
            name='photo',
            field=models.CharField(default=123, max_length=100),
            preserve_default=False,
        ),
    ]
