# Generated by Django 3.0.3 on 2020-03-12 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webexample', '0011_auto_20200312_1155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='date',
        ),
        migrations.RemoveField(
            model_name='book',
            name='date',
        ),
        migrations.RemoveField(
            model_name='genre',
            name='date',
        ),
    ]
